#!/bin/bash
# FlowLife Quick Start Script

echo "🚀 FlowLife Setup Helper"
echo "========================"
echo ""
echo "1. SUPABASE SETUP:"
echo "   - Öffne deine Supabase Online-Instanz"
echo "   - SQL Editor → cleanup_and_setup.sql ausführen"
echo ""
echo "2. DOMAIN SETUP:"
echo "   - DNS A-Record: flowlife.frankrath.de → 162.55.42.202"
echo "   - In Coolify: Neue Static Site App erstellen"
echo ""
echo "3. N8N WEBHOOKS:"
echo "   - Login: https://automatisierung.frankrath.de"
echo "   - Import: n8n_workflow_mail_sender.json"
echo ""
echo "4. TEST LOKAL:"
echo "   npx create-react-app flowlife-client"
echo "   cd flowlife-client"
echo "   # Copy React component from Claude"
echo "   npm start"
echo ""
echo "5. DEPLOY:"
echo "   npm run build"
echo "   scp -r build/* frank@162.55.42.202:/home/frank/flowlife/client/"
echo ""
echo "✅ Fertig! App läuft auf https://flowlife.frankrath.de"
